SELECT 
    (?countryLabel as ?country) (GROUP_CONCAT(DISTINCT ?borderLabel;separator=";") AS ?borders) (GROUP_CONCAT(DISTINCT ?continentLabel;separator=";") AS ?continents) 
    (SAMPLE(?capitalLabel) AS ?capital) (GROUP_CONCAT(DISTINCT ?currencyLabel;separator=";") AS ?currencies) 
    (GROUP_CONCAT(DISTINCT ?languageLabel;separator=";") AS ?languages) (SAMPLE(?area) AS ?area) (SAMPLE(?population) AS ?population) 
    (SAMPLE(?gdp) AS ?gdp) (SAMPLE(?populationDensity) AS ?populationDensity) (SAMPLE(?hdi) AS ?hdi)
{
    SELECT ?countryLabel ?borderLabel ?capitalLabel ?continentLabel ?currencyLabel ?languageLabel ?area ?population ?gdp ?populationDensity ?hdi
    WHERE {
    {
        SELECT 
            ?country ?border ?continent (SAMPLE(?capital) AS ?capital) ?currency ?language (SAMPLE(?area) AS ?area) (SAMPLE(?population) AS ?population) 
            (SAMPLE(?gdp) AS ?gdp) (SAMPLE(?populationDensity) AS ?populationDensity) (SAMPLE(?hdi) AS ?hdi)
        WHERE {
            ?country wdt:P31 wd:Q3624078.
            ?country wdt:P47 ?border.
            ?country wdt:P30 ?continent.
            ?country wdt:P36 ?capital.
            ?country wdt:P38 ?currency.
            ?country wdt:P37 ?language.
            ?country wdt:P2046 ?area.
            ?country wdt:P1082 ?population.
            ?country wdt:P2132 ?gdp.
            ?country wdt:P1081 ?hdi.
            BIND(?population/?area AS ?populationDensity).
        }  
        GROUP BY ?country ?border ?currency ?language ?continent
    }
    SERVICE wikibase:label {bd:serviceParam wikibase:language "en".}
    } 
}
GROUP BY ?countryLabel